pull_request_rules:
  - name: Automatic merge for snapshot branch when CI passes and author is elasticmachine or apmmachine
    conditions:
      - or:
        - author=elasticmachine
        - author=apmmachine
      - and:
        - check-success=package-storage/pr-merge
        - base=snapshot
    actions:
      merge:
        method: squash
