---
description: Pipeline for ingesting APM application logs.
processors:
  - grok:
      field: observer.version
      pattern_definitions:
        DIGITS: (?:[0-9]+)
      patterns:
        - '%{DIGITS:observer.version_major:int}.%{DIGITS:observer.version_minor:int}.%{DIGITS:observer.version_patch:int}(?:[-+].*)?'
  - fail:
      if: ctx.observer.version_major > 8 || (ctx.observer.version_major == 8 && ctx.observer.version_minor > 1)
      message: Document produced by APM Server v{{{observer.version}}}, which is newer than the installed APM integration (v8.1.0). The APM integration must be upgraded.
  - remove:
      field:
        - observer.version_minor
        - observer.version_patch
      ignore_missing: true
