---
description: Pipeline for ingesting APM profile data.
processors:
  - grok:
      field: observer.version
      pattern_definitions:
        DIGITS: (?:[0-9]+)
      patterns:
        - '%{DIGITS:observer.version_major:int}.%{DIGITS:observer.version_minor:int}.%{DIGITS:observer.version_patch:int}(?:[-+].*)?'
  - fail:
      if: ctx.observer.version_major > 8 || (ctx.observer.version_major == 8 && ctx.observer.version_minor > 1)
      message: Document produced by APM Server v{{{observer.version}}}, which is newer than the installed APM integration (v8.1.0). The APM integration must be upgraded.
  - remove:
      field:
        - observer.version_minor
        - observer.version_patch
      ignore_missing: true
  - user_agent:
      field: user_agent.original
      ignore_failure: true
      ignore_missing: true
      target_field: user_agent
  - geoip:
      database_file: GeoLite2-City.mmdb
      field: client.ip
      ignore_missing: true
      on_failure:
        - remove:
            field: client.ip
            ignore_failure: true
            ignore_missing: true
      target_field: client.geo
